export const ACTION_TYPES = { 
    START_CONNECT:1,
    SEND_INIT_DATA:2,
    REGISTERED:3,
    REGISTER_FAILED:4,
    SENDER_CONNECTED:5,
    SENDER_DISCONNECTED:6,
    ON_CONNECTION_ERROR:7,
    SET_FIELD:8
};

export const MobileState = {        
    INITIALIZING:1,      
    DISCONNECTED:2,
    ERROR:3, 
    WAITING_FOR_MOBILE:4,
    MOBILE_CONNECTED:5
};

